### ISSUE TITLE
Allow specifying line length

### ISSUE THREAD

**Issue by volskaya** [emacs-lsp/lsp-dart#53]
Other code editors allow to specify line length for the formatter. Could you implement [that](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration) into lsp-dart as well?

**Comment by ericdallo** [comment]
I think this is an option passed to the dart SDK on the LSP serer initialization, I'll confirm that, thank you!

**Comment by ericdallo** [comment]
Hey @volskaya, I checked it and the dart SDK server currently does not has this support yet, It seems that VSCode has this because it uses another deprecated analyzer from DartSDK that has that

Anyway, I [opened an issue](https://github.com/dart-lang/sdk/issues/43043) on Dart SDK to see if this can be implemented.

**Comment by ericdallo** [comment]
@volskaya, It's lsp-dart fault, I'll try to release a new version supporting this today!

**Comment by ericdallo** [comment]
Added support for that on `lsp-dart` `1.15.0`, note that this is only supported after `Dart SDK` `2.10`: https://github.com/dart-lang/sdk/commit/ba459f96cfe020e8d6b01f527959e5e1bb900508
