### ISSUE TITLE
LSP only connects for one buffer

### ISSUE THREAD

**Issue by aemoncannon** [emacs-lsp/lsp-dart#65]
**Describe the bug**

The first buffer I open connects to the analyzer and everything works great.

Any subsequent file I open the connection fails. I get this printed to *Messages*:
"Error running timer ‘lsp--on-idle’: (error "The connected server(s) does not support method textDocument/documentHighlight.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")"

Also noticed that lsp--buffer-workspace is nil

**To Reproduce**
Here's my .emacs
https://gist.github.com/aemoncannon/5a1c09986551d62a7783443c2f6c98b7

**Expected behavior**
Multiple files all sharing the same connection.

**Version**
[LSP Dart] 1.17.1 (package: 20200916.103) at 2020.09.16 @ Emacs 27.1
[Dart SDK] Dart SDK version: 2.9.3 (stable) (Unknown timestamp) on "linux_x64"

**Comment by ericdallo** [comment]
You probably didn't imported correctly your project to lsp, take a look if `lsp-describe-session` is correct, also you can add your project with `lsp-workspace-folders-add`.

When you open your project for the first time, lsp asks something like this:
![image](https://user-images.githubusercontent.com/7820865/93418165-1fb9e400-f880-11ea-81f9-a2f67f8464da.png)
Choose the `i` option if the path is right, otherwise choose `I` and input the correct project path

**Comment by aemoncannon** [comment]
Ok, I think I figured it out. I hadn't set the value of lsp-dart-flutter-sdk-dir, so it was searching for it in /usr/bin/flutter and failing to initialize properly. Once I fixed this, the other buffers now get a workplace properly. Thanks

**Comment by ericdallo** [comment]
Nice :)
